services:
  valkey:
    image: valkey/valkey:latest
    container_name: valkey
    ports:
      - "6379:6379"
    # volumes:
    #   - valkey_data:/data
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
    # volumes:
    #   - qdrant_data:/qdrant/storage
    restart: unless-stopped